name: Matrix Node pipeline

on:
   workflow_dispatch:

jobs:
   node:
     runs-on: [self-hosted, wsl-salim]
     strategy:
       matrix:
         node-version: [16, 24]
     steps:
        - name: Clone code
          uses: actions/checkout@v7

        - name: Node install
          uses: actions/setup-node@v6
          with:
            node-version: ${{ matrix.node-version }}
        
        - name: Install Dependencies
          run: npm install

        - name: Run Application
          run: | 
            node app.js &
            sleep 5 
            curl http://localhost:8080
            curl http://localhost:8080/health
            pkill -f "node app.js"
            
