name: Sonarqube pipeline

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  sonarqube:
     runs-on: [self-hosted, wsl-salim]

     steps:
       - name: Clone code
         uses: actions/checkout@v7

       - name: Sonarqube Scan
         uses: SonarSource/sonarqube-scan-action@v8
         with:
           args: >
              -Dsonar.projectKey=NodeApp 
              -Dsonar.sources=. 
              -Dsonar.host.url=${{ vars.SONAR_HOST_URL }}
              -Dsonar.login=${{ secrets.SONAR_TOKEN}}
